// ACTIONS CONSTANTS FOR NOTES

export const FETCH_NOTES_REQUEST = "FETCH_NOTES_REQUEST";
export const FETCH_NOTES_SUCCESS = "FETCH_NOTES_SUCCESS";
export const FETCH_NOTES_FAILURE = "FETCH_NOTES_FAILURE";
export const ADD_NOTES ="ADD_NOTES"
export const UPDATE_NOTES ="UPDATE_NOTES"
export const DELETE_NOTES ="DELETE_NOTES"

// ACTIONS CONSTANTS FOR login
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";


// actionj creators